version: "3"

services:
  go_app:
    build:
      context: .
      dockerfile: Dockerfile  # Build the Go app from the Dockerfile
    container_name: go_app
    expose:
      - "8080"  # The internal port that the Go app listens on

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  # Expose port 80 on the host machine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the NGINX config file
    depends_on:
      - go_app  # Ensure NGINX starts after the Go app is up
